### ISSUE TITLE
animateDuration differs to much for different device types 

### ISSUE THREAD

**Issue by Allmedialab** [kyco/jquery.kyco.preloader#4]
Hi,
Thanks for the wonderful plugin!

I implemented your script in a Bootstrap 4 website with Ajaxify and it's working fine.
[https://www.wilart.nl](url) please have a look at "Schilderijen", "Krijtborden", or "Kussens".

Only thing I wonder is it possible to change the  "animateDuration" for different OSes or device types. Did notice on the iPad IOS and Android mobile Phones, that it loads much slower. Tested the website on blazing fast internet.

Warm Regards & Thanks,
David

**Comment by caweidmann** [comment]
Hi @Allmedialab 

You can manually change the `animateDuration` for different devices and operating systems, e.g. to change it for iPad and iPhone you could do something like:

    animateDuration: navigator.userAgent.match(/(iPhone|iPad)/) ? 200 : 500

I will also check if there is perhaps something in the code that executes differently on mobile devices.

**Comment by Allmedialab** [comment]
> I will also check if there is perhaps something in the code that executes differently on mobile devices

That would be great!  Thanks David

**Comment by caweidmann** [comment]
Hi

I have looked at the code and there is nothing I can find that runs differently on mobile than on desktop.

I see in your code you are using the `forceSequentialLoad` flag and you have set it to `true`. Because you are hiding the images while you are loading them there is no need to set this flag to true. It will actually force images to be loaded in the order that it finds them in the DOM. This can potentially increase the loading time as the images are not being downloaded in parallel. I would suggest setting this flag to `false` to see if that improves performance (if you don't set the flag it will be false by default - so you can actually leave it off completely).

These are your current options you are passing:
```
$('.fadein-div').kycoPreload({
  showInContainer: true,
  useOpacity: true,
  forceSequentialLoad: true,
  animateDuration: 200,
  fadeOutDuration: 1000,
  afterEach: function() {
    $(this).fadeIn(1000); // $(this) refers to image that was preloaded.
  },
  beforeComplete: function() {
    console.log('images preloaded, fading out the overlay and loader at 1.5s');
  },
  onComplete: function() {
    console.log('AllMediaLab at your service!');
  }
});
```
I would use the following options (you don't need any of the other options as you are not using them):
```
$('.fadein-div').kycoPreload({
  showInContainer: true,
  useOpacity: true,
  animateDuration: 200,
  fadeOutDuration: 1000,
});
```

Please try the code above. From my side there is nothing else I can do.

PS: I tested with Chrome on Android the pages https://www.wilart.nl/schilderij-look-behind-the-curtain and https://www.wilart.nl/schilderij-blue-lagoon-one and I couldn't notice a difference in load times compared to using Chrome on desktop.
